name: auto-format
run-name: Ensuring code style maintained
on:
  push:
    branches:
      - master
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: prettier
        run: npm run format
      - name: Check for modified files
        id: git-check
        run: |
          echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'CI Autoformatter [bot]'
          git add -A
          git diff --staged --quiet || git commit -m "Automated changes by CI bot"
          git push
