name: auto-format
run-name: Ensuring code style maintained
on:
  push:
    branches:
      - master
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}
      - name: prettier
        run: |
          npx prettier --write "**/*.{ts, tsx, js, jsx, html, css, json}"
      - name: Check for modified files
        id: git-check
        run: |
          echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'CI Autoformatter [bot]'
          git commit -am "Automated changes by prettier"
          git push
